# Upload the Data and Read the .csv File

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('salaries_by_college_major.csv')

In [4]:
df.head()

Undergraduate Major  Starting Median Salary  Mid-Career Median Salary  \
0             Accounting                 46000.0                   77100.0   
1  Aerospace Engineering                 57700.0                  101000.0   
2            Agriculture                 42600.0                   71900.0   
3           Anthropology                 36800.0                   61500.0   
4           Architecture                 41600.0                   76800.0   

   Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary  \
0                            42200.0                           152000.0   
1                            64300.0                           161000.0   
2                            36300.0                           150000.0   
3                            33800.0                           138000.0   
4                            50600.0                           136000.0   

      Group  
0  Business  
1      STEM  
2  Business  
3      HASS  
4  Business

# Preliminary Data Exploration

In [5]:
df.shape

(51, 6)

In [6]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [7]:
df.isna()

Undergraduate Major  Starting Median Salary  Mid-Career Median Salary  \
0                 False                   False                     False   
1                 False                   False                     False   
2                 False                   False                     False   
3                 False                   False                     False   
4                 False                   False                     False   
5                 False                   False                     False   
6                 False                   False                     False   
7                 False                   False                     False   
8                 False                   False                     False   
9                 False                   False                     False   
10                False                   False                     False   
11                False                   False                     False   
12                False                   False                     False   
13                False                   False                     False   
14                False                   False                     False   
15                False                   False                     False   
16                False                   False                     False   
17                False                   False                     False   
18                False                   False                     False   
19                False                   False                     False   
20                False                   False                     False   
21                False                   False                     False   
22                False                   False                     False   
23                False                   False                     False   
24                False                   False                     False   
25                False                   False                     False   
26                False                   False                     False   
27                False                   False                     False   
28                False                   False                     False   
29                False                   False                     False   
30                False                   False                     False   
31                False                   False                     False   
32                False                   False                     False   
33                False                   False                     False   
34                False                   False                     False   
35                False                   False                     False   
36                False                   False                     False   
37                False                   False                     False   
38                False                   False                     False   
39                False                   False                     False   
40                False                   False                     False   
41                False                   False                     False   
42                False                   False                     False   
43                False                   False                     False   
44                False                   False                     False   
45                False                   False                     False   
46                False                   False                     False   
47                False                   False                     False   
48                False                   False                     False   
49                False                   False                     False   
50                False                    True                      True   


# Data Cleaning

In [8]:
df.tail()

Undergraduate Major  Starting Median Salary  Mid-Career Median Salary  \
46             Psychology                 35900.0                   60400.0   
47               Religion                 34100.0                   52000.0   
48              Sociology                 36500.0                   58200.0   
49                Spanish                 34000.0                   53100.0   
50  Source: PayScale Inc.                     NaN                       NaN   

    Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary Group  
46                            31600.0                           127000.0  HASS  
47                            29700.0                            96400.0  HASS  
48                            30700.0                           118000.0  HASS  
49                            31000.0                            96400.0  HASS  
50                                NaN                                NaN   NaN

In [9]:
clean_df = df.dropna()

In [11]:
clean_df.tail()

Undergraduate Major  Starting Median Salary  Mid-Career Median Salary  \
45   Political Science                 40800.0                   78200.0   
46          Psychology                 35900.0                   60400.0   
47            Religion                 34100.0                   52000.0   
48           Sociology                 36500.0                   58200.0   
49             Spanish                 34000.0                   53100.0   

    Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary Group  
45                            41200.0                           168000.0  HASS  
46                            31600.0                           127000.0  HASS  
47                            29700.0                            96400.0  HASS  
48                            30700.0                           118000.0  HASS  
49                            31000.0                            96400.0  HASS

In [13]:
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

# Accessing Columns and Individual Cells in a DataFrame

In [14]:
clean_df['Starting Median Salary'].max()

74300.0

In [15]:
clean_df['Starting Median Salary'].idxmax()

43

In [17]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [25]:
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [19]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [23]:
clean_df['Mid-Career Median Salary'].idxmax()

8

In [24]:
clean_df['Mid-Career Median Salary'][8]

107000.0

In [26]:
clean_df['Undergraduate Major'][8]

'Chemical Engineering'

The college major with the highest mid-career salary is 'Chemical Engineering'.
The graduates with the above major earn $107000.0

In [27]:
clean_df['Starting Median Salary'].min()

34000.0

In [29]:
clean_df['Starting Median Salary'].idxmin()

49

In [31]:
clean_df.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

The college major with the lowest starting salary is 'Spanish'. The graduates with the above major earn $34000.0

In [32]:
clean_df['Mid-Career Median Salary'].idxmin()

18

In [33]:
clean_df.loc[18]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

The college major with the lowest mid-career salary is 'Education'. The graduates with the above major earn $52000.0

In [34]:
clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

# Sorting Values and Adding Columns

In [35]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1,  'Spread', spread_col)
clean_df.head()

Undergraduate Major    Spread  Starting Median Salary  \
0             Accounting  109800.0                 46000.0   
1  Aerospace Engineering   96700.0                 57700.0   
2            Agriculture  113700.0                 42600.0   
3           Anthropology  104200.0                 36800.0   
4           Architecture   85400.0                 41600.0   

   Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
0                   77100.0                            42200.0   
1                  101000.0                            64300.0   
2                   71900.0                            36300.0   
3                   61500.0                            33800.0   
4                   76800.0                            50600.0   

   Mid-Career 90th Percentile Salary     Group  
0                           152000.0  Business  
1                           161000.0      STEM  
2                           150000.0  Business  
3                           138000.0      HASS  
4                           136000.0  Business

In [36]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [37]:
top_degrees = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
top_degrees[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [38]:
high_risk = clean_df.sort_values('Spread', ascending=False)
high_risk[['Undergraduate Major', 'Spread']].head()

Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

# Grouping and Pivoting Data with Pandas

In [41]:
clean_df.groupby('Group').count()

Undergraduate Major  Spread  Starting Median Salary  \
Group                                                           
Business                   12      12                      12   
HASS                       22      22                      22   
STEM                       16      16                      16   

          Mid-Career Median Salary  Mid-Career 10th Percentile Salary  \
Group                                                                   
Business                        12                                 12   
HASS                            22                                 22   
STEM                            16                                 16   

          Mid-Career 90th Percentile Salary  
Group                                        
Business                                 12  
HASS                                     22  
STEM                                     16

In [44]:
clean_df.groupby('Group').mean()

<ipython-input-44-61aa9b47bd8a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  clean_df.groupby('Group').mean()


Spread  Starting Median Salary  Mid-Career Median Salary  \
Group                                                                       
Business  103958.333333            44633.333333              75083.333333   
HASS       95218.181818            37186.363636              62968.181818   
STEM      101600.000000            53862.500000              90812.500000   

          Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary  
Group                                                                           
Business                       43566.666667                      147525.000000  
HASS                           34145.454545                      129363.636364  
STEM                           56025.000000                      157625.000000

In [48]:
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean()

<ipython-input-48-149c56babcd5>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  clean_df.groupby('Group').mean()


Spread  Starting Median Salary  Mid-Career Median Salary  \
Group                                                                   
Business 103,958.33               44,633.33                 75,083.33   
HASS      95,218.18               37,186.36                 62,968.18   
STEM     101,600.00               53,862.50                 90,812.50   

          Mid-Career 10th Percentile Salary  Mid-Career 90th Percentile Salary  
Group                                                                           
Business                          43,566.67                         147,525.00  
HASS                              34,145.45                         129,363.64  
STEM                              56,025.00                         157,625.00

# Webscrape Payscale's Website

In [140]:
from bs4 import BeautifulSoup
import requests

In [175]:
all_ranks = []
all_majors = []
all_early_pay = []
all_mid_pay = []
all_high_meaning = []

for page_no in range(1, 33):
  payscale_response = requests.get(url=f"https://www.payscale.com/college-salary-report/majors-that-pay-you-back/bachelors/page/{page_no}")
  payscale_response.raise_for_status()
  payscale_soup = BeautifulSoup(payscale_response.text, "html.parser")

  payscale_ranks = payscale_soup.find_all(class_="data-table__cell csr-col--rank")
  payscale_majors = payscale_soup.find_all(class_="data-table__cell csr-col--school-name")
  payscale_metrics =  payscale_soup.find_all(class_="data-table__cell csr-col--right")

  for each_rank in range(len(payscale_ranks)):
    all_ranks.append(int(payscale_ranks[each_rank].find(class_="data-table__value").string))
    all_majors.append(payscale_majors[each_rank].find(class_="data-table__value").string)

  for each_pay in range(0, len(payscale_metrics), 3):
    all_early_pay.append(int(payscale_metrics[each_pay].find(class_="data-table__value").string.replace('$','').replace(',','')))

  for each_pay in range(1, len(payscale_metrics), 3):
    all_mid_pay.append(int(payscale_metrics[each_pay].find(class_="data-table__value").string.replace('$','').replace(',','')))

  for each_pay in range(2, len(payscale_metrics), 3):
    if payscale_metrics[each_pay].find(class_="data-table__value").string == "-":
      all_high_meaning.append(payscale_metrics[each_pay].find(class_="data-table__value").string)
    else:
      all_high_meaning.append(int(payscale_metrics[each_pay].find(class_="data-table__value").string.replace('%','')))

In [177]:
payscale_dict = {
    "Rank": all_ranks,
    "Major": all_majors,
    "Early Career Pay": all_early_pay,
    "Mid-Career Pay": all_mid_pay,
    "% High Meaning": all_high_meaning
}
payscale_df = pd.DataFrame(payscale_dict)
payscale_df

Rank                                         Major  Early Career Pay  \
0       1                         Petroleum Engineering             97500   
1       2  Operations Research & Industrial Engineering             98300   
2       3                            Interaction Design             74700   
3       4              Applied Economics and Management             76500   
4       5                              Building Science             69000   
..    ...                                           ...               ...   
794   795                                Equine Studies             40300   
795   796                         Addictions Counseling             45900   
796   797                      Nonprofit Administration             42800   
797   798                     Early Childhood Education             41700   
798   799                                 Metalsmithing             44700   

     Mid-Career Pay % High Meaning  
0            212500             61  
1            191800             21  
2            173600             54  
3            164400             54  
4            163100             47  
..              ...            ...  
794           52500             50  
795           52200             78  
796           52100             72  
797           50600             77  
798           44900             36  

[799 rows x 5 columns]

In [178]:
payscale_df.to_csv("payscale.csv")